<?php

/**
 * @file
 * EC Shipping Widget module.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_theme().
 */
function ec_shipping_widget_theme($existing, $type, $theme, $path): array {
  return [
    'form_element__radio__shipping_method' => [
      'base hook' => 'form_element',
    ],
  ];
}

/**
 * Implements hook_theme_suggestions_form_element_alter().
 */
function ec_shipping_widget_theme_suggestions_form_element_alter(array &$suggestions, array $variables): void {
  $element = $variables['element'];
  $name = $element['#name'] ?? '';
  $type = $element['#type'] ?? '';

  if ($type === 'radio' && str_contains($name, 'shipping_method')) {
    $suggestions[] = 'form_element__' . str_replace('-', '_', $element['#type']) . '__shipping_method';
  }
}

/**
 * Implements hook_form_alter().
 */
function ec_shipping_widget_form_alter(&$form, FormStateInterface $form_state, $form_id): void {
  if (!str_starts_with($form_id, 'commerce_checkout_flow')) {
    return;
  }

  if (!isset($form['shipping_information']['shipments'])) {
    return;
  }

  $form['#attached']['library'][] = 'ec_shipping_widget/styles';
}
